PUT http://localhost:5000/api/v1/ticket/808b3671-4896-4785-b3a7-b9d9bee22852
Accept: application/json

{
  "vehicle": "ABC1246",
  "parkingSlot": "B1-A158"
}
### GET ticket
GET http://localhost:5000/api/v1/ticket/4fcb42b4-1055-4c1e-90d5-761add9837e8
Accept: application/json

### Create new ticket
POST https://gentle-oasis-89232.herokuapp.com/api/v1/ticket
Content-Type: application/json

{
  "vehicle": "ABC1246",
  "parkingSlot": "B1-A154"
}

### Get all tickets
GET http://localhost:5000/api/v1/tickets
Accept: application/json

###

